-- Sales requisitions (digital HMS release form)
CREATE TABLE IF NOT EXISTS `sales_requisitions` (
  `id` CHAR(36) NOT NULL,
  `tenant_id` CHAR(36) NOT NULL,
  `req_number` VARCHAR(40) NOT NULL,
  `lead_id` CHAR(36) NOT NULL,
  `contact_id` CHAR(36) NULL,
  `deal_id` CHAR(36) NULL,
  `product_id` CHAR(36) NULL,
  `stock_unit_id` CHAR(36) NULL,
  `serial_no` VARCHAR(80) NULL,
  `product_name` VARCHAR(191) NULL,
  `qty` DECIMAL(15, 3) NOT NULL DEFAULT 1,
  `advance_amount` DECIMAL(15, 2) NOT NULL DEFAULT 0,
  `payment_notes` TEXT NULL,
  `status` ENUM('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'FULFILLED', 'CANCELLED') NOT NULL DEFAULT 'PENDING_APPROVAL',
  `requested_by_id` CHAR(36) NOT NULL,
  `approved_by_id` CHAR(36) NULL,
  `approved_at` DATETIME(3) NULL,
  `rejected_reason` VARCHAR(500) NULL,
  `invoice_id` CHAR(36) NULL,
  `shipped_at` DATETIME(3) NULL,
  `notes` TEXT NULL,
  `custom_fields` JSON NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  `deleted_at` DATETIME(3) NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `sales_requisitions_tenant_id_req_number_key` (`tenant_id`, `req_number`),
  KEY `sales_requisitions_tenant_id_status_created_at_idx` (`tenant_id`, `status`, `created_at`),
  KEY `sales_requisitions_tenant_id_lead_id_idx` (`tenant_id`, `lead_id`),
  KEY `sales_requisitions_tenant_id_stock_unit_id_idx` (`tenant_id`, `stock_unit_id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
