export { ProductsPage } from './ProductsPage'
export { ProductCreatePage } from './ProductCreatePage'
export { ProductDetailPage } from './ProductDetailPage'
export { InventoryPage } from './InventoryPage'
export { InvoicesPage } from './InvoicesPage'
export { ApprovedReleasesPage } from './ApprovedReleasesPage'
export { PurchaseOrdersPage } from './PurchaseOrdersPage'
export { SuppliersPage } from './SuppliersPage'
export { BrandsPage } from './BrandsPage'
export { SpareStockPage } from './SpareStockPage'
export { InventoryHubPage, InventoryHubRedirect } from './InventoryHubPage'
export { StockMovePage } from './StockMovePage'
export { DeliveryChallansPage } from './DeliveryChallansPage'
